### ISSUE TITLE
Why do you not upload this AppImage to Bintray from Travis CI like your other AppImages?

### ISSUE THREAD

**Issue by fusion809** [probonopd/Emacs.AppImage#1]
Hi,

[My fork](https://github.com/fusion809/Emacs.AppImage) of this repo uploads its build of this AppImage to my Bintray AppImages repository and I am wondering why this one doesn't? Your AppImage is less than 60 MB in size so it is more than small enough to fit on Bintray. Was there some other reason why you don't upload your Emacs AppImage to Bintray?

Thanks for your time,
Brenton

**Comment by probonopd** [comment]
Hi Brenton, all the AppImages on https://bintray.com/probono/AppImages are generated from https://github.com/probonopd/AppImages and serve as examples for upstreams with the intent that upstreams will eventually "adopt" them. This here is more a one-off experiment because I don't really think the GNU project will care about providing binaries.
